### ISSUE TITLE
Usability enhancements with WPF app - EPIC

### ISSUE THREAD

**Issue by christiannagel** [CodebreakerApp/Codebreaker.Xaml#45]
- [ ] Style for start, set move buttons
- [ ] Use VSM with game mode change, add animations
- [ ] Radial gradient colors with pegs
- [ ] Dark and light theme
